#pragma once
#include "stdafx.h"


#define LSA_CREDS_DISPLAY_RAW				0x00000000
#define LSA_CREDS_DISPLAY_LINE				0x00000001
#define LSA_CREDS_DISPLAY_NEWLINE			0x00000002

#define LSA_CREDS_DISPLAY_CREDENTIAL		0x08000000
#define LSA_CREDS_DISPLAY_PRIMARY			0x01000000
#define LSA_CREDS_DISPLAY_CREDENTIALKEY		0x02000000
#define LSA_CREDS_DISPLAY_CREDENTIAL_MASK	0x07000000

#define LSA_CREDS_DISPLAY_KERBEROS_10		0x00100000
#define LSA_CREDS_DISPLAY_KEY_LIST			0x00200000
#define LSA_CREDS_DISPLAY_CREDMANPASS		0x00400000
#define LSA_CREDS_DISPLAY_PINCODE			0x00800000
#define LSA_CREDS_DISPLAY_KERBEROS_10_1607	0x00010000

#define LSA_CREDS_DISPLAY_CLOUDAP_PRT		0x00001000

#define LSA_CREDS_DISPLAY_NODECRYPT			0x10000000
#define LSA_CREDS_DISPLAY_WPASSONLY			0x20000000
#define LSA_CREDS_DISPLAY_DOMAIN			0x40000000
#define LSA_CREDS_DISPLAY_SSP				0x80000000

typedef struct _LSA_OS_CONTEXT {
	DWORD MajorVersion;
	DWORD MinorVersion;
	DWORD BuildNumber;
} LSA_OS_CONTEXT, * PLSA_OS_CONTEXT;

typedef struct _LSA_CONTEXT {
	HANDLE hProcess;
	LSA_OS_CONTEXT osContext;
} LSA_CONTEXT, * PLSA_CONTEXT;

typedef struct _LSA_LIB {
	PROCESS_VERY_BASIC_MODULE_INFORMATION Informations;
	BOOL isPresent;
	BOOL isInit;
} LSA_LIB, * PLSA_LIB;

typedef struct _LSA_PACKAGE {
	BOOL isValid;
	const wchar_t* ModuleName;
	LSA_LIB Module;
} LSA_PACKAGE, * PLSA_PACKAGE;

typedef NTSTATUS(*PLSA_ACQUIRE_KEYS_FUNCS) (PLSA_CONTEXT cLsass, PPROCESS_VERY_BASIC_MODULE_INFORMATION lsassLsaSrvModule);
typedef NTSTATUS(*PLSA_INIT) ();

extern LSA_PACKAGE LsassPackage;

extern LSA_CONTEXT cLsass;

extern PWORD g_fParameter_UseLogonCredential;
extern PWORD g_IsCredGuardEnabled;

BOOL AcquireLSA();
BOOL EnumerateLSA();
BOOL FindModules(PPROCESS_VERY_BASIC_MODULE_INFORMATION pModuleInformation);